Config files improvements
NilFoundation/placeholder pull request #208
Opened 2024-12-16 09:16 UTC by ioxid

`.clang-format`: preserve include blocks groups (instead of grouping all the includes and sorting them)
`.envrc`: allow specifying used derivation in environment (mainly so that whoever uses clang could just set `PLACEHOLDER_DEVELOP_DERIVATION` to `.#develop-clang`)
`.gitignore`: add vscode, direnv and cmake related files
`CMakeLists.txt`: enable tests in root too (so it works without `nix develop`)
`flake.nix`: add `develop-clang` derivation

2024-12-16 09:54 UTC, ioxid commented
Not sure how the 4 tests got removed...

2024-12-17 11:33 UTC, Iluvmagick approved these changes

2024-12-17 16:43 UTC, AndreyMlashkin requested changes

2024-12-17 16:43 UTC, AndreyMlashkin commented on CMakeLists.txt
> +
Please, wait for the CI of this PR
https://github.com/NilFoundation/placeholder/pull/213

Let's see, if it changes the number of tests

2024-12-18 08:56 UTC, AndreyMlashkin commented on CMakeLists.txt
> +
As I see, it's exactly about this line...
https://github.com/NilFoundation/placeholder/pull/213

2024-12-19 09:29 UTC, AndreyMlashkin approved these changes

2024-12-19 09:36 UTC, merged