175 ecdsa in bbf
NilFoundation/placeholder pull request #219
Opened 2024-12-20 15:40 UTC by AntoineCyr

2024-12-30 17:07 UTC, ayashunsky requested changes
I am not sure that requested changes are sufficient, but I do believe they are necessary. I also think that more comments (i.e. moving some of the documentation from Notion into code) could benefit flexible_multiplication code. It was pretty useless with the old syntax, but now should be rather helpful.

2025-01-02 15:23 UTC, AntoineCyr commented on crypto3/libs/algebra/include/nil/crypto3/algebra/primes.hpp
> +                nil::crypto3::multiprecision::montgomery_big_mod_rt<Bits> divisor(0u, n),
That is correct

2025-01-02 15:32 UTC, AntoineCyr commented on crypto3/libs/algebra/include/nil/crypto3/algebra/curves/detail/vesta/types.hpp
> +                        using extended_integral_type = typename base_field_type::extended_integral_type;
I will ask them

2025-01-02 15:33 UTC, AntoineCyr commented on crypto3/libs/algebra/include/nil/crypto3/algebra/fields/field.hpp
> +                    typedef nil::crypto3::multiprecision::big_uint<16 * modulus_bits> extended_integral_type;
It is taken from the original repo https://github.com/NilFoundation/crypto3/blob/f15b449729ba51a52ec28d15985cd894cb943d80/libs/algebra/include/nil/crypto3/algebra/fields/field.hpp#L53
It has the mention
` // TODO(martun): check why extended integral type must be 16x wider.`

We can let the multiprecision team work this out when I ask them to reintegrate extended_integral_type

2025-01-02 15:50 UTC, AntoineCyr commented on crypto3/libs/blueprint/test/bbf/detail/range_check_multi.cpp
> +            if (j % for_faulty_chunks != 0) {
I don't see any in it either, I kept the original test as is. I will change it for simplicity

2025-01-02 16:48 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/flexible_multiplication.hpp
> +                        Check_Mod_P c1 = Check_Mod_P(context_object, R,PP,num_chunks,bit_size_chunk,false,make_links);
I will do that, but I do not follow why it would need to be true for a subcomponents if it is false for the whole component. 
Actually let me change my question. 
In my mind make_links would need be be true everywhere. 
What are the reason we would want any component such as flexible_multiplication to not have copy constraints?

2025-01-02 16:50 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/flexible_multiplication.hpp
> +                        Check_Mod_P c1 = Check_Mod_P(context_object, R,PP,num_chunks,bit_size_chunk,false,make_links);
Also since you said most of the times and not all the times, what would be the reason for a subcomponent to use the make_links of the component?

2025-01-02 18:12 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/check_mod_p.hpp
> +                            constrain(ca.res_c);
Yes, that make sense  for me now

2025-01-02 19:08 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/check_mod_p.hpp
> +                            constrain(ca.res_c);
Replacing that constrain with a copy_constrain, the circuit is still satisfied when the copy constraint is violated.
I get:
```
[2025-01-02 14:05:33.608799] [0x00000001035e0580] [warning] Assignment violates copy constraint (1 != 0)
Is_satisfied = 1
```
Is that expected?

2025-01-02 19:16 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/range_check_multi.hpp
> +                            allocate(C[i]);
I thought we needed to allocate any cell we constrain.
I removed the line, however I still get the cell issue if I use the theoretical minimum.

2025-01-02 19:27 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/range_check_multi.hpp
> +                                constrain(YI[i] - Y[i][num_rc_chunks - 1] *
Yes you are right it works, we don't need YI

2025-01-02 19:58 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/flexible_multiplication.hpp
> +                        //Range_Check rc = Range_Check(context_object, R,num_chunks,bit_size_chunk,make_links);
So we would need a range_check on PP as well? Because check_mod_p is basically an addition of Q and PP

2025-01-02 21:42 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/carry_on_addition.hpp
> +                        }
I am not sure what you mean, `C[num_chunks-1]` is the last carry?
It is equal to 1 if `X[num_chunks-1] + Y[num_chunks-1] + C[num_chunks-2] > BASE`

2025-01-02 21:44 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/flexible_multiplication.hpp
> +                        if constexpr (stage == GenerationStage::ASSIGNMENT) {
Which part? I am not sure what to look for, similarly to the comment above

2025-01-03 13:50 UTC, ayashunsky commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/check_mod_p.hpp
> +                            constrain(ca.res_c);
No, it isn't. I guess it deserves a special investigation. We should probably both look into it.

2025-01-03 14:33 UTC, ayashunsky commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/check_mod_p.hpp
> +                            constrain(ca.res_c);
Expecting a fix in master soon

2025-01-03 14:34 UTC, ayashunsky commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/range_check_multi.hpp
> +                            allocate(C[i]);
Do you get to the minimum once the YI are removed?

2025-01-03 14:35 UTC, ayashunsky commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/flexible_multiplication.hpp
> +                        if constexpr (stage == GenerationStage::ASSIGNMENT) {
I explained above, maybe it helps here too

2025-01-03 15:21 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/range_check_multi.hpp
> +                            allocate(C[i]);
No still not

2025-01-03 15:22 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/carry_on_addition.hpp
> +                        }
Ahhh, ok I was scared I was missing something big hahaha, yeah I'll fix this

2025-01-03 15:25 UTC, ayashunsky commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/range_check_multi.hpp
> +                            allocate(C[i]);
I think this deserves investigation. Maybe you can try counting allocations, to find the excessive use of cells?

2025-01-04 19:38 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/check_mod_p.hpp
> +                            constrain(ca.res_c);
Fix is working

2025-01-04 19:45 UTC, AntoineCyr commented on crypto3/libs/blueprint/test/bbf/algebra/fields/non_native/flexible_multiplication.cpp
> +    using NonNativeFieldVariant = std::variant<crypto3::algebra::curves::pallas::base_field_type,
The main issue with that is that the integral_type cannot be defined at runtime inside the circuit, and we cannot pas the type as a function argument.
We are currently defining all the specific type beforehand, and at runtime we specify which one we use.
```
                    using NonNativeIntegralVariant = std::variant<
                        nil::crypto3::multiprecision::big_uint<2* crypto3::algebra::curves::pallas::base_field_type::modulus_bits>,
                        nil::crypto3::multiprecision::big_uint<2* crypto3::algebra::curves::vesta::base_field_type::modulus_bits>
                    >;
```
But we still need a parameter to specify which type of the 2 specified we want to use.

If we want to avoid the non native field parameter with the current architecture, I see 2 possible approach:

1. Only pass in the index instead of a type. For instance index 0 would be pallas, and index 1 would be vesta.
2. Use an extended type big enough to handle the biggest extended field. That way we would not need to pass in any parameter and just use the default extended type.

2025-01-06 15:45 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/range_check_multi.hpp
> +                            allocate(C[i]);
So basically everything needs to fit in 2 rows + 1

2025-01-07 08:55 UTC, ayashunsky commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/range_check_multi.hpp
> +                            allocate(C[i]);
Ok, then the question is: why does it start at column 5?

2025-01-07 08:57 UTC, ayashunsky commented on crypto3/libs/blueprint/test/bbf/algebra/fields/non_native/flexible_multiplication.cpp
> +    using NonNativeFieldVariant = std::variant<crypto3::algebra::curves::pallas::base_field_type,
I have some thoughts on that, but we'll have to discuss in detail

2025-01-07 14:31 UTC, ayashunsky commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/detail/range_check_multi.hpp
> +                            allocate(C[i]);
Sorry, I don't get that :(

2025-01-08 14:40 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/check_mod_p.hpp
> +                                      std::size_t num_chunks, std::size_t bit_size_chunk,bool expect_overflow,
Should we store the constant 0 in a constant column instead of a public input column?

2025-01-22 12:28 UTC, ayashunsky requested changes

2025-01-22 12:28 UTC, ayashunsky commented on crypto3/libs/blueprint/test/CMakeLists.txt
> -    "bbf/no_assignment_checks"
Changes show that some of CMakeLists.txt lines were deleted. That's pretty wierd... Why would we do smth like that?

2025-01-22 12:46 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/flexible_multiplication.hpp
> +                                ZERO = 0;
Yes I agree, I overlooked this

2025-01-22 12:56 UTC, AntoineCyr commented on crypto3/libs/blueprint/test/CMakeLists.txt
> -    "bbf/no_assignment_checks"
Had some issues with the rebase, fixed this

2025-01-22 13:01 UTC, AntoineCyr commented on crypto3/libs/blueprint/include/nil/blueprint/bbf/components/algebra/fields/non_native/flexible_multiplication.hpp
> +                            NonNativeFieldTypeIndex<NonNativeFieldType>::value, NonNativeIntegralExtendedVariant>;
No it is still needed.
The variant is used to create the extended types of all specified types. The only way to get rid of this is to have the extended type defined inside the field file definitions.

We need the variant because the extended type need to exist before runtime. The variant create both types beforehand, and then we use NonNativeFieldType to select which type we need

2025-01-22 13:06 UTC, AntoineCyr commented on crypto3/libs/blueprint/test/CMakeLists.txt
> -    "bbf/no_assignment_checks"
Actually, now that I added the test backs the pipeline is failing because of it. I'll investigate later

2025-01-22 21:10 UTC, AntoineCyr commented on crypto3/libs/blueprint/test/CMakeLists.txt
> -    "bbf/no_assignment_checks"
Fixed

2025-01-23 15:58 UTC, ayashunsky approved these changes

2025-01-23 17:20 UTC, merged