Cosmetics
NilFoundation/placeholder pull request #55
Opened 2024-10-03 09:49 UTC by AndreyMlashkin

2024-10-04 10:37 UTC, akokoshn requested changes

2024-10-07 08:24 UTC, AndreyMlashkin commented on .gitignore
> +/*/*.c
We always had the following lines in .gitignore:

```
# Ignore stuff in the top level dir that shouldn't be checked in
/*.c
/*.cpp
/*.h
...
```
I just want to extend this logic to the sub-folders.

2024-10-07 09:09 UTC, akokoshn commented on .gitignore
> +/*/*.c
it's make sense only if used different `.gitignore` for root folder and subfoleders.
We are using single one, so let's not ignore the meaningful files.

2024-10-07 09:49 UTC, AndreyMlashkin commented on .gitignore
> +/*/*.c
Ok, I will remove these lines then

2024-10-07 09:51 UTC, AndreyMlashkin commented on .gitignore
> +/*/*.c
done

2024-10-07 11:46 UTC, akokoshn approved these changes

2024-10-07 11:46 UTC, merged