Use multithreaded assigner
NilFoundation/placeholder pull request #57
Opened 2024-10-03 11:43 UTC by AndreyMlashkin

2024-10-03 14:07 UTC, akokoshn requested changes
Please check parallel-crypto3 headers carefully.
Any idea how to check automatically i used right headers? May be  some static-assert?

2024-10-04 09:39 UTC, AndreyMlashkin commented
> Please check parallel-crypto3 headers carefully. Any idea how to check automatically i used right headers? May be some static-assert?

I don't think it's possible. Because, come of the includes should still point to the single-threaded implementation.

2024-10-04 10:48 UTC, AndreyMlashkin commented on parallel-crypto3/libs/parallel-containers/include/nil/parallel-crypto3/container/accumulation_vector.hpp
done

2024-10-07 08:54 UTC, akokoshn requested changes
What about includes in transpiler and zkevm-frameowrk ((should use #ifdef MULTITHREAD) )

2024-10-07 08:54 UTC, akokoshn commented on proof-producer/bin/proof-producer/CMakeLists.txt
> +            target_compile_definitions(${ARG_TARGET_NAME}-lib INTERFACE MULTITHREADED)
check if `lib` is `parallel-crypto3`.
Generally single-thread version also can has some additional dependency

2024-10-11 09:43 UTC, closed without merging